--- 
- hosts: 172.31.24.33
  become: yes
  tasks:
      - name: i want to run linux command 
        command: uname
        register: myresult
      - name: i want to display linux command output 
        debug:
            msg: "{{myresult}}"  

      - name: i want to install wget 
        apt: 
            name: wget
            state: present

      - name: i want to install tree
        apt: 
            name: tree
            state: present            