--- 
- hosts: 172.31.24.33
  become: yes
  tasks:
      - name: i want to run linux command 
        command: hostname
        register: myresult
      - name: i want to display linux command output 
        debug:
            msg: "{{myresult}}"  