--- 
-  hosts: 172.31.15.160
   become: yes
   tasks: 
     - include_tasks: myfile.yml
    
    
     - name: i want to install tree
       apt: 
           name: tree
           state: present     

                     
              
     