--- 
- hosts: mywebserver
  become: yes 
  tasks:
      - name: i want to install java 8 version on ubuntu node
        apt:
           name: "{{myjavaonubuntu}}"
           state: present
        when: ansible_os_family== "Debian"


      - name: i want to install java 8 version on RadHat node
        yum:
           name: "{{myjavaonRedHat}}"
           state: present
        when: ansible_os_family== "RadHat"  
