---
- hosts: 172.31.24.33
  become: yes
  vars:
   myvar1: tree
   myvar2: wget
   yvar3: git
  tasks: 
     - name: i want to display vars value 
       debug:
            msg: "{{myvar1}}"
     - name: i want to install package 
       apt:
         name: "{{item}}"
         state: present 
         when: ansible_os_family=="debian"
         loop:
               - "{{ myvar1}}"
               - "{{myvar2}}" 

            
      
      
      

