--- 
- hosts: my DB
  become: yes 
  tasks: 
      - name: i want to install apache on ubuntu node 
        apt: 
            name: apache2
            state: present
        when: ansible_os_family =="Debian"
        
      - name: i want to start webserver on ubuntu server
        service:
            name: apache2
            state: started
        when: ansible_os_family =="Debian"
      

      - name: i want to install apache on redHat node
        yum:
            name: httpd
            state: present
        when: ansible_os_family =="RedHat"
      
      - name: i want to start/stop webserver on redHat node
        service:
            name: httpd
            state: started
        when: ansible_os_family =="RedHat"