--- 
- hosts: mywebserver
  become: yes 
  tasks: 
      - name: i want to install apache on ubuntu node 
        apt: 
            name: "{{mywebserveronubuntu}}"
            state: present
        when: ansible_os_family == "Debian"
        
      - name: i want to start webserver on ubuntu server
        service:
            name: "{{mywebserveronubuntu}}"
            state: started
        when: ansible_os_family == "Debian"
      

      - name: i want to install apache on redHat node
        yum:
            name: "{{mywebserveronRedHat}}"
            state: present
        when: ansible_os_family == "RedHat"
      
      - name: i want to start/stop webserver on redHat node
        service:
            name: "{{mywebserveronRedHat}}"
            state: started
        when: ansible_os_family == "RedHat"