--- 
# Step 3.1 — /temp directory on your server
#- name: i want to create directory tem
  #file:
        #path: /home/ubuntu/temp
        #state: directory

# Step 3.2 — download tomcat tar file in temp directory
- name: download tomcat tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
    dest: /home/ubuntu/temper
    force_basic_auth: yes


# Step 3.3 — /opt/tomcat directory on your server
- name: i want to create directory temp
  file:
        path: /opt/tomcat
        state: directory

# Step 3.4 — extract the archive file to  /opt/tomcat 
- name: i want to extract the tomcat file to /opt/tomcat
  command:
    cmd: sudo tar xzvf /home/ubuntu/temper -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE
