--- 
# step 4.1 : Give the tomcat group ownership over the entire installation directory:
- name: Recursively change ownership of a directory /opt/tomcat
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat 


# step 4.2 : Give the tomcat group read access to the conf directory
- name: give the tomcat group read access to the conf directory
  file:
    path: /opt/tomcat/conf
    recurse: yes
    owner: tomcat
    group: tomcat
    mode: g+r

# step 4.3 : Give the tomcat group execute  access to the conf directory
- name: give the tomcat group execute access to the conf directory
  file:
    path: /opt/tomcat/conf
    recurse: yes
    owner: tomcat
    group: tomcat
    mode: g+x# 
    
# step 4.1.1 : Give the tomcat user  the owner of webpass
- name: make the tomcat user  the owner of webpass
  file:
    path: /opt/tomcat/webpass
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat 

# step 4.1.2 : Give the tomcat user  the owner of webpass
- name: make the tomcat user  the owner of work
  file:
    path: /opt/tomcat/work
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

# step 4.1.3 : Give the tomcat user  the owner of temp
- name: make the tomcat user  the owner of temp
  file:
    path: /opt/tomcat/temp
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

# step 4.1.3 : Give the tomcat user  the owner of logs
- name: make the tomcat user  the owner of logs
  file:
    path: /opt/tomcat/logs
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

